spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    url: jdbc:mysql://localhost:3306/theaterdb?useSSL=false
    username: root
    password: admin
  jpa:
    hibernate:
      properties:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: validate
